version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "stats:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  producer:
    image: peterc/kafka-flask-producer-example:latest
    build:
      context: ./producer
    ports:
      - "8282:80"
    depends_on:
      - kafka
    entrypoint: ["python3", "app.py"]
    volumes:
      - ./producer/src:/app
      
  consumer:
    image: peterc/kafka-flask-consumer-example:latest
    build:
      context: ./consumer
    ports:
      - "8283:80"
    depends_on:
      - kafka
    entrypoint: ["python3", "app.py"]
    volumes:
      - ./consumer/src:/app          

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication"
    depends_on:
      - kafka
      - zookeeper
    command: export myvar=123; echo $myvar

  webview:
    image: sourcelaborg/kafka-webview:latest
    ports:
     - "8080:8080"
    volumes:
     - kafkawebview_data:/app/data
    depends_on:
      - kafka
      - zookeeper

volumes: 
 kafkawebview_data:
