version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  producer:
    image: peterc/jbhh-producer-example:latest
    ports:
      - "8282:80"
    volumes:
       - ./producer/src:/app

  consumer:
    image: peterc/jbhh-consumer-example:latest
    ports:
      - "8283:80"
    volumes:
       - ./consumer/src:/app
